dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc: 
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

dotenv: .env

wallets:
  from_wallet: ${PRIVATE_KEY}


networks:
  kovan:
    eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"